### ISSUE TITLE
Not generating reports.

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/genet#6]
I dunno if I'm missing something.

https://github.com/bucharest-gold/roi/blob/master/benchmark/benchmark.js#L82-L90

But is generating nothing [console, file or flamegraph] .

Steps to reproduce:
- Clone roi
- npm install 
- npm run benchmark

**Comment by lance** [comment]
Please upgrade your `genet` dependency to version 0.0.2. When using the `bench` module, you can stop profiling by providing a function property on `exports.done` ([example](https://github.com/bucharest-gold/fidelity/blob/master/benchmark/profile.js#L31-L36)).

Let me know if this works for you.
